// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFl2r-oJSBZYt0tac-uZkxQshGZXSRPc',
    appId: '1:488372966900:web:362cc77b28c87d1cabd5a1',
    messagingSenderId: '488372966900',
    projectId: 'spoken-cafe-456813-b3e6d',
    authDomain: 'spoken-cafe-456813-b3e6d.firebaseapp.com',
    databaseURL: 'https://spoken-cafe-456813-b3e6d-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-456813-b3e6d.firebasestorage.app',
    measurementId: 'G-QDTED2MM63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXY_nKvO6CuHS-6KOj6bM1Vf4yRRsLxPg',
    appId: '1:488372966900:android:1c9f3e71e1302a5eabd5a1',
    messagingSenderId: '488372966900',
    projectId: 'spoken-cafe-456813-b3e6d',
    databaseURL: 'https://spoken-cafe-456813-b3e6d-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-456813-b3e6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXg3l8muLAurvwEBWfhbK-UzRl4c8kZ4s',
    appId: '1:488372966900:ios:dd09961d295838e2abd5a1',
    messagingSenderId: '488372966900',
    projectId: 'spoken-cafe-456813-b3e6d',
    databaseURL: 'https://spoken-cafe-456813-b3e6d-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-456813-b3e6d.firebasestorage.app',
    iosClientId: '488372966900-pfqepee4pq9jh0dhguujskcla659kha6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spokencafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXg3l8muLAurvwEBWfhbK-UzRl4c8kZ4s',
    appId: '1:488372966900:ios:dd09961d295838e2abd5a1',
    messagingSenderId: '488372966900',
    projectId: 'spoken-cafe-456813-b3e6d',
    databaseURL: 'https://spoken-cafe-456813-b3e6d-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-456813-b3e6d.firebasestorage.app',
    iosClientId: '488372966900-pfqepee4pq9jh0dhguujskcla659kha6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spokencafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFl2r-oJSBZYt0tac-uZkxQshGZXSRPc',
    appId: '1:488372966900:web:3e1ab694e8415a57abd5a1',
    messagingSenderId: '488372966900',
    projectId: 'spoken-cafe-456813-b3e6d',
    authDomain: 'spoken-cafe-456813-b3e6d.firebaseapp.com',
    databaseURL: 'https://spoken-cafe-456813-b3e6d-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-456813-b3e6d.firebasestorage.app',
    measurementId: 'G-YC8T6P088P',
  );

}