// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8_hYC-IENhvvBmmSiSUx2cQOjTAf0rg',
    appId: '1:324717418314:android:afd7d7f338629fcf6a93b3',
    messagingSenderId: '324717418314',
    projectId: 'spoken-cafe-4d3f0',
    databaseURL: 'https://spoken-cafe-4d3f0-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-4d3f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmToZeb3oNd_-JiSsIGXA19r7pE08KCcY',
    appId: '1:324717418314:ios:cf02ca42104cd5906a93b3',
    messagingSenderId: '324717418314',
    projectId: 'spoken-cafe-4d3f0',
    databaseURL: 'https://spoken-cafe-4d3f0-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-4d3f0.firebasestorage.app',
    androidClientId: '324717418314-k4msfp5808urj0m6jj5q07kanle4bs4s.apps.googleusercontent.com',
    iosClientId: '324717418314-a4lgckflhitbr7kdn12vm7o27n5uqsho.apps.googleusercontent.com',
    iosBundleId: 'com.example.spokenCafeController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmToZeb3oNd_-JiSsIGXA19r7pE08KCcY',
    appId: '1:324717418314:ios:cf02ca42104cd5906a93b3',
    messagingSenderId: '324717418314',
    projectId: 'spoken-cafe-4d3f0',
    databaseURL: 'https://spoken-cafe-4d3f0-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-4d3f0.firebasestorage.app',
    androidClientId: '324717418314-k4msfp5808urj0m6jj5q07kanle4bs4s.apps.googleusercontent.com',
    iosClientId: '324717418314-a4lgckflhitbr7kdn12vm7o27n5uqsho.apps.googleusercontent.com',
    iosBundleId: 'com.example.spokenCafeController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN7eb7ubIVBUeWwXtusDVnZj7gmxTyDWs',
    appId: '1:324717418314:web:4080574e358c25146a93b3',
    messagingSenderId: '324717418314',
    projectId: 'spoken-cafe-4d3f0',
    authDomain: 'spoken-cafe-4d3f0.firebaseapp.com',
    databaseURL: 'https://spoken-cafe-4d3f0-default-rtdb.firebaseio.com',
    storageBucket: 'spoken-cafe-4d3f0.firebasestorage.app',
    measurementId: 'G-77Z4VP7TWW',
  );
}
